repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: pytest-check
        name: Unit tests
        entry: poetry run pytest
        language: system
        pass_filenames: false
      - id: mypy-check
        name: Static check
        entry: poetry run mypy .
        language: system
        pass_filenames: false
      - id: black-check
        name: Check code formatting
        entry: poetry run black . --check
        language: system
        pass_filenames: false
      - id: flake8-check
        name: Check PEP8
        entry: poetry run flake8
        language: system
        pass_filenames: false
      - id: isort-check
        name: Check imports
        entry: poetry run isort . --check
        language: system
        pass_filenames: false
