language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# enable cache for Python dependencies
cache: pip

# restrict to branches
branches:
  only:
    - master

# commands to install python dependencies
install:
  # the features used in setup.cfg require at decent version of setuptools
  - python -m pip install --upgrade "setuptools>=46.4.0"

  # install dependencies for test
  - python -m pip install -e ".[tests]"

# commands to run tests
script:
  # run tests
  - python -m coverage run -m pytest

  # run static analysis
  - if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]]; then python -m mypy .; fi

  # run code formatting tests
  - python -m black . --check
  - python -m flake8

# commands to manage tests results
after_script:
  # show coverage stats
  - python -m coverage report -m

  # upload coverage stats to codecov.io
  # codecov token is stored in travis settings
  - python -m codecov -X gcov
