language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

# enable cache for Python dependencies
cache: pip

# restrict to branches
branches:
  only:
    - master

before_install:
  # install poetry
  - pip install poetry

# commands to install python dependencies
install:
  # install dependencies for test
  - poetry install

# commands to run tests
script:
  # run tests
  - poetry run pytest --cov-report term

  # run static analysis
  - if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]]; then poetry run mypy .; fi

  # run code formatting tests
  - poetry run black . --check
  - poetry run pflake8
  - poetry run isort . --check

# commands to manage tests results
after_script:
  # upload coverage stats to codecov.io
  # codecov token is stored in travis settings
  - poetry run codecov -X gcov
