name: Continuous integration

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest

        python-version:
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v4

      - uses: abatilo/actions-poetry@v2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-ansi

      - name: Tests
        run: poetry run pytest --cov-report term

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  static-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: abatilo/actions-poetry@v2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install dependencies
        run: poetry install --no-ansi

      - name: Mypy static analysis
        run: poetry run mypy . --check

      - name: Black code style check
        run: poetry run black . --check

      - name: Flake8 code style check
        run: poetry run flake8

      - name: Isort imports check
        run: poetry run isort . --check
